# Generated by Django 3.2.12 on 2022-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('advance_pay', models.PositiveIntegerField()),
                ('pay_method', models.CharField(max_length=255)),
                ('event', models.ManyToManyField(blank=True, null=True, related_name='suppliers', to='events.Event')),
            ],
        ),
    ]
